spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: dbuser
    password: dbpass
  logging:
    level:
      com.example.springmybatis.repository: DEBUG

mybatis:
  configuration:
    map-underscore-to-camel-case: true

cors:
  allowedOrigins:
    - "http://localhost:5173"
    - "https://spring-teachers-system.vercel.app"
